### ISSUE TITLE
Add the ability to describe all configs in several files

### ISSUE THREAD

**Issue by dromix** [metarhia/metaconfiguration#100]
## Is your feature request related to a problem? Please describe.

In my opinion, there are many files in config directory, it would be great to have possibility, to describe env variables in few files.

## Describe the solution you'd like

Map by specific file names, set order priorities and highest priority for files as it was before.

## Describe alternatives you've considered

It realized in [node-config file-load-order](https://github.com/node-config/node-config/wiki/Configuration-Files#file-load-order)

#### **`development.js`**
```js
({
   server: { host: '0.0.0.0' },
   database: { 
     host: process.env.DB_HOST, 
     port: process.env.DB_PORT,
     schema: process.env.DB_SCHEMA
   },
   authSecret: process.env.AUTH_SECRET,
   //...
})
```
#### **`test.js`**
```js
({
   server: { host: '127.0.0.1' },
   database: { 
     host: '127.0.0.1', 
     port: 5432,
     schema: 'test_db'
   },
   authSecret: 'test_auth_secret',
   //...
})
```

**Comment by tshemsedinov** [comment]
We support something like this. You can put different configurations to `server.dev.js`, `server.test.js`, `server.prod.js`, etc. Before starting `node server` you can set environment variable `MODE=dev` to select one of prefixes.
